### ISSUE TITLE
README.md discrepancies

### ISSUE THREAD

**Issue by martinmarty** [s60sc/PicoWebServer#1]
Perhaps the Espressif page has been revised since you wrote the README.md and the links do not work or do not describe the actual content of the page. https://www.espressif.com/en/products/socs/esp8266ex/resources

- The name "ESP8266 NonOS AT Bin" does not exist but perhaps it has been renamed, is "ESP8266 IDF AT Bin (Latest)" the one we want?
- The "Flashing tool" link gets a 404 but the tools seem to be on the Resources page.
- The "Instructions" link is correct.

Thank you.

![Screenshot 2021-02-26 020450](https://user-images.githubusercontent.com/10269204/109267110-0e81e580-77d7-11eb-9b8b-dc696990bef7.JPG)
![Screenshot 2021-02-26 022242](https://user-images.githubusercontent.com/10269204/109268791-92d56800-77d9-11eb-9266-1d9ed535bb17.JPG)

**Comment by s60sc** [comment]
Thanks for the heads up. Espressif have changed their website and removed a lot of firmware. I cant test the latest version as my boards are at a different location. If you are willing to try and report back success then that would be useful.

**Comment by martinmarty** [comment]
I would love to help with this but I am afraid too much of it is over my head. Apparently the boards I have are nodemcu 8266 boards which is not what we need. This is what I have currently:
https://www.ebay.com/itm/NodeMcu-Lua-WIFI-Internet-Things-development-board-based-ESP8266-CP2102-module/201542946669?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649
[https://i.ebayimg.com/images/g/OmcAAOSwPYFfYGLz/s-l400.jpg]<https://www.ebay.com/itm/NodeMcu-Lua-WIFI-Internet-Things-development-board-based-ESP8266-CP2102-module/201542946669?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649>
NodeMcu Lua WIFI Internet Things Development Board ESP8266 CP2102 for Arduino | eBay<https://www.ebay.com/itm/NodeMcu-Lua-WIFI-Internet-Things-development-board-based-ESP8266-CP2102-module/201542946669?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649>
ESP8266 has IO Pin. A great set of tools to develop ESP8266! hope you could understand. Product Details.
www.ebay.com

It seems that what we need is something like this:
https://www.amazon.com/SongHe-ESP8266-ESP-01S-Serial-Transceiver/dp/B088KMHH1H/ref=sr_1_3?crid=3N67EHDP0Y2LF&dchild=1&keywords=esp01s&qid=1614410431&sprefix=esp01%2Caps%2C183&sr=8-3
Amazon.com: SongHe ESP8266 ESP-01S WiFi Serial Transceiver Module with 1MB Flash DIP-8 3-6V(Pack of 5PCS): Computers &amp; Accessories<https://www.amazon.com/SongHe-ESP8266-ESP-01S-Serial-Transceiver/dp/B088KMHH1H/ref=sr_1_3?crid=3N67EHDP0Y2LF&dchild=1&keywords=esp01s&qid=1614410431&sprefix=esp01%2Caps%2C183&sr=8-3>
Buy SongHe ESP8266 ESP-01S WiFi Serial Transceiver Module with 1MB Flash DIP-8 3-6V(Pack of 5PCS): Network Transceivers - Amazon.com ✓ FREE DELIVERY possible on eligible purchases
www.amazon.com

Where I get stuck is that all those boards that I see say 1MB flash, but in the current "ESP8266-IDF-AT_V2.1.0.0.zip" file from Espressif the file that I think I would want to load, factory/factory_WROOM-02.bin is 2097152 bytes so I don't see how it could possibly fit on these boards. Here is what I am looking at:
https://docs.espressif.com/projects/esp-at/en/latest/AT_Binary_Lists/ESP8266_AT_binaries.html
Released Firmware — ESP-AT User Guide documentation<https://docs.espressif.com/projects/esp-at/en/latest/AT_Binary_Lists/ESP8266_AT_binaries.html>
Provide feedback about this document. Next Previous. © Copyright 2020, Espressif Systems (Shanghai) Co., Ltd. Revision 8e83329b.
docs.espressif.com
What are your thoughts? Am I looking at the wrong stuff? I don't mind buying some stuff to experiment with if you can get me pointed in the right direction. Thanks! -Marty

________________________________

**Comment by s60sc** [comment]
Any ESP8266 can host the AT firmware, the board doesn't matter.  I've put a copy of the old firmware in this repository so you can use that. When I have the opportunity I'll look at the latest firmware.

**Comment by martinmarty** [comment]
I ordered the following and will install the AT fw on it and try the http code on Pico. I had already downloaded the file "ESP8266_NonOS_AT_Bin_V1.7.4.zip" from Espressif so that is good because at least I picked out the right file! I'll let you know how it goes. I think that where I was getting off track was looking at the WROOM-02 fw an not realizing that it is a completely different and newer wifi module with 2MB flash.
https://www.amazon.com/gp/product/B07V54DWXH/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
